# Generated by Django 4.2.5 on 2023-11-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0005_alter_customuser_name_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='services',
            name='rate',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
