# Generated by Django 4.2.5 on 2023-11-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0006_remove_customuser_user_type_services_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
