# Generated by Django 4.2.5 on 2023-12-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0009_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='sid',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='uid',
            new_name='user',
        ),
    ]
