# Generated by Django 4.2.5 on 2023-12-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0010_rename_sid_orders_service_rename_uid_orders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
