# Generated by Django 4.2.5 on 2023-12-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0011_alter_orders_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
