# Generated by Django 4.2.5 on 2023-12-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0012_orders_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
